### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#10]
Hello

I wanted to know if there are any plans to support arm platform? I want to run Jump over the Raspberry Pi so that I can access my dashboard on both mobile and laptop.

I previously had generated ARM images successfully but I am no longer able to do so. The error I am getting is below 

```
 => ERROR [linux/arm64 builder 3/3] RUN composer install --no-dev   --optimize-autoloader   --no-interaction   --no-progress                                                                                   0.2s
 => CANCELED [linux/arm/v7 builder 2/3] COPY jumpapp/ /app                                                                                                                                                     0.0s
------
 > [linux/arm64 builder 3/3] RUN composer install --no-dev   --optimize-autoloader   --no-interaction   --no-progress:
------
Dockerfile:5
--------------------
   4 |     COPY jumpapp/ /app
   5 | >>> RUN composer install --no-dev \
   6 | >>>   --optimize-autoloader \
   7 | >>>   --no-interaction \
   8 | >>>   --no-progress
   9 |     
--------------------
error: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c composer install --no-dev   --optimize-autoloader   --no-interaction   --no-progress" did not complete successfully: exit code: 1
```
I understand that arm images are not officially supported but any help or pointers in this regard would be highly appreciated.

Thanks.

**Comment by daledavies** [comment]
I'd actually love to support ARM, I think hosting Jump on a Raspberry Pi is a pretty likely use case given the nature of what Jump was created for... a lightweight front end for a self-hosted environment.

It looks like building images that target ARM should be straight forward on an x86 device but the blocker for me right now is not having a Raspberry Pi to test on.

I'll keep this issue on the back burner for now until I get stuck into the 1.1.0 milestone and hopefully I'll work something out soon. I do intend to buy a Raspberry Pi soon but that might get not happen for a few months.

That error message references qemu, how are you trying to build the image? What platform and command are you running etc?

**Comment by daledavies** [comment]
Thanks for taking the time to raise these issue btw, it is encouraging to see people wanting to use Jump 😀

**Comment by quaintdev** [comment]
I am following this [tutorial](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/) for Linux. I was able to successfully generate the image after a failed attempt few days back but now it's not working. The command that I used is `docker buildx build --platform linux/arm,linux/arm64 -t quaintdev/jump . --push`

Platform: Linux (Debian 11) amd64

**Comment by daledavies** [comment]
I'll take a look and also keep you posted on the situation regarding arm images. Currently couldn't buy a Raspberry Pi anyway, completely sold out!

**Comment by Just5KY** [comment]
I have built an image for armv7 and arm64 https://hub.docker.com/r/justsky/jump

`docker buildx build --push --platform linux/arm/v7,linux/arm64/v8  --tag justsky/jump .`

```yml
version: '3'
services:
  jump:
    image: justsky/jump
    container_name: jump
    restart: unless-stopped
    ports:
      - 8321:8080
    volumes:
      -  $DOCKERDIR/jump/backgrounds:/backgrounds
      -  $DOCKERDIR/jump/sites:/sites
    environment:
      SITENAME: 'SkyPi'
```

![image](https://user-images.githubusercontent.com/71321862/158870780-953ca1b5-b4ed-456e-be48-020e99c579f5.png)

Everything is running fine as far as I have tested.

**Comment by daledavies** [comment]
Awesome, thank you for testing this.

**Comment by quaintdev** [comment]
I can finally use this beautiful start page. Also, I appreciate how lite this is.

@daledavies and @Just5KY Thanks!

**Comment by daledavies** [comment]
Amazing, thanks. I'll get buildx set up over the weekend and get an "official" arm build pushed to docker hub. 

I'm interested if there should be a single multiarch image or separate images for ARM Vs amd64. Maybe the "latest" tag should be multiarch with separate arch and version tags.

A few people have mentioned that they like that the Jump.image it small so I'm concerned about the size of a multiarch image.

**Comment by Just5KY** [comment]
@daledavies 
You can have 1 multiarch image
No need for having separate tags for every arch

**Comment by daledavies** [comment]
I've built a multiarch image for the latest release... v1.1.2 and "latest" tags on Docker Hub. Let me know if this works for you :)
