### ISSUE TITLE
Not an issue but request/idea

### ISSUE THREAD

**Issue by wabj** [daledavies/jump#103]
I love this dashboard, I've moved to it from Heimdall as it just looks better. Would it be possible though to get an interface to easily add/remove/edit items on it?

But not have an awful in your face link to an secure admin panel, maybe just a little cog in the corner?

**Comment by Z1mDMan** [comment]
I second this idea. Please, and thank you for jump!

**Comment by daledavies** [comment]
I've always said that I don't want to design an admin interface for Jump, so I'm closing this issue for now.

I may be tempted to create this as a separate application, to be run in a different container however.
