### ISSUE TITLE
Cache favicons

### ISSUE THREAD

**Issue by djjudas21** [daledavies/jump#106]
Hi there, I'm experimenting with Jump and if I get on with it, I plan to contribute a Helm chart.

I like the auto retrieval of favicons for sites, and this will be my main way of using Jump as I don't want to bother populating the icons manually. However I notice that the icons aren't cached, and are retrieved every time the page is loaded, which is quite slow.

It would be awesome if the retrieved favicons got cached, either in `/sites/icons` or in a separate cache dir.

**Comment by daledavies** [comment]
Howdy, they are totally cached and the latest release improves this caching too... https://github.com/daledavies/jump/blob/main/jumpapp/classes/Site.php#L60:)

Try with the latest release and see if you're still having an issue?

Also do you perhaps have the cachebypass option set?

**Comment by djjudas21** [comment]
Hey, thanks for your response. I'm not passing any configuration for `CACHEBYPASS` but judging by [README](https://github.com/daledavies/jump/blob/main/README.md?plain=1#L81) it looks like it defaults to `true` if not specified. I'll try setting it explicitly and check out the latest release too. Thanks!

**Comment by djjudas21** [comment]
Confirmed, manually setting `CACHEBYPASS: false` fixes this

**Comment by daledavies** [comment]
Glad you got it sorted 😃
