### ISSUE TITLE
Pull time from system locale.

### ISSUE THREAD

**Issue by deanfourie1** [daledavies/jump#109]
Thanks for this.

This is stupid.

Why not just use the system locale.

In my case, I host a lot of my services hosted on a VLAN without internet connection. What is the need to query an external API for time? I understand to pull weather but I don't even use that feature.

Surely there's a way to pull the time from the system?

_Originally posted by @deanfourie1 in https://github.com/daledavies/jump/issues/105#issuecomment-2041053852_

**Comment by daledavies** [comment]
Thanks, you have just reminded me why I've been struggling to stay motivated on this project. Calling me stupid is not going to get me motivated.

**Comment by deanfourie1** [comment]
> Thanks, you have just reminded me why I've been struggling to stay motivated on this project. Calling me stupid is not going to get me motivated.

No haha, I'm not calling you stupid! 

I just hate how so many of this stuff is now cloud dependent.

This is one of the best app launchers I've found in terms of design and functionality in comparison to the 10+ others i've tried.

Maybe I should have worded that better. My appologies.
