### ISSUE TITLE
Font characters like "g" get cut off

### ISSUE THREAD

**Issue by Coolykoen** [daledavies/jump#110]
Heya, been using jump and its great, however, i have seen something weird and now i can't un-see it haha.

Jump seems to cut off the bottom of long characters.
Letter "g" is a good example as you can see here:
![image](https://github.com/daledavies/jump/assets/48558949/13fecee0-cffa-4bbb-a966-b59274535ce2)
That's at normal 100% zoom.
If i zoom out or in, it seems to work correctly for the following zoom levels:
50% (below 50 it's too hard to read so i can't check)
70%
80%
90%
120%
190%
230% (haven't checked higher than that)
^ i just checked, both Edge and Firefox behave this way, but on edge the "working" zoom levels differ a bit.

this is at 230%:
![image](https://github.com/daledavies/jump/assets/48558949/32bf05b9-cb84-423f-910c-ee3bb07b3f4e)

**Comment by daledavies** [comment]
Ha interesting, thanks for reaching out. Never noticed that before but it looks like a simple CSS issue
 I'll take a look 😃

**Comment by daledavies** [comment]
I've pushed a CSS tweak that I think should fix this, it won't be available on docker hub until I create the next release though.

**Comment by Coolykoen** [comment]
No problem, i will check again when the time comes haha

**Comment by daledavies** [comment]
Wondering if you've had a chance to test this? Thanks so much 😁

**Comment by Coolykoen** [comment]
Oh sorry, didn't realize i could still reply to closed issues! Yes, is seems to work fine, thank you for the update. :)
hmm weird, i swear it was closed when i looked last time, but i see now its still opened. maybe i was just blind haha.

**Comment by daledavies** [comment]
Awesome thanks for confirming
