### ISSUE TITLE
Disable status check option

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#124]
I could not find any option to disable the status check of websites. Is there any way disable the same?

**Comment by daledavies** [comment]
There's one do disable the feature entirely but not a way to disable it on a per-site basis.

We could make it though, is that what you're after?

**Comment by quaintdev** [comment]
I mean global status check only. I missed the `CHECKSTATUS` flag from documentation. Thanks. Closing this issue.

**Comment by cinderblockgames** [comment]
> There's one do disable the feature entirely but not a way to disable it on a per-site basis.
> 
> We could make it though, is that what you're after?

Did this get made?  I would like it to be per-site so that I can include external links without having them get checked.
