### ISSUE TITLE
Weather error

### ISSUE THREAD

**Issue by Jogai** [daledavies/jump#14]
Something is going wrong with the weather api key:
![image](https://user-images.githubusercontent.com/1233188/158887450-6b6c33f3-1dee-49da-92a0-77407b090fed.png)
Error
![image](https://user-images.githubusercontent.com/1233188/158887506-ec25c3d5-28c4-4fb0-aad2-5bad40de675d.png)

**Comment by daledavies** [comment]
The API key will show as "1" there, the JUMP.owmapikey  global variable is just used to tell the front end that you supplied an API key in config. 

I'll take a look as soon as I can.

**Comment by daledavies** [comment]
Really hard to tell from these screenshots what might be going wrong, have you definitely got a correct OpenWeather API key?

If so could you show was was returned from weatherdata.php?

**Comment by Jogai** [comment]
It was something to do with my network. It didn't resolve openweathermap.org correct (although my browser did)

**Comment by daledavies** [comment]
Perhaps the way Jump handles this situation could be improved, I'll keep it in mind for future development.

Thanks for letting me know and closing the issue 😀
