### ISSUE TITLE
API to add url remotely

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#17]
This is a feature request.  I was thinking something like a REST endpoint that supports GET method. Basically we just send the entire url as a GET request to server and it will add that url to the json config. This way users don't have to login to their servers every time they need to add  new site. It might work something like this

1. User visits url `https://startpage.example.com/?url=http://github.com` 
2. Users request is processed and a new url is added to sites.json
3. Once the json is updated, a new shortcut github.com is added to homepage by fetching icon and title of the page.

I believe the icon part is already implemented in jump, title we might have to think about. We could also use additional query parameters to specify tags for certain url but that can be done in future versions. I myself would have picked this up but I have background in Go and have not worked with PHP.

What do you think?

**Comment by daledavies** [comment]
Thanks for your interest in Jump, but I'm not going to implement this as it is way beyond the scope of what I want to do with this project.

I don't like the idea of giving write access to the sites file and don't want to implement something like oauth and a proper rest API.

**Comment by quaintdev** [comment]
No problem. I understand. 

I was not hoping for oauth or authentication. Just API that could update the shortcuts. But I understand your concern of doing that without proper security.

Anyway I'll see if I can run a tiny API server to update json and get my requirement fullfilled.
