### ISSUE TITLE
Open links in new tabs

### ISSUE THREAD

**Issue by darrenleesmith** [daledavies/jump#20]
Is it possible to add an open in new tab function? I have attempted to use the Homer way (target: "_blank") but it doesn't work

**Comment by daledavies** [comment]
This is an awesome idea and shouldn't take long to implement. I'll see what I can do today for you 😀

**Comment by daledavies** [comment]
This has been implemented in the v1.1.3 release, just need to push the docker image to docker hub. Thanks for your input, much appreciated 😄

**Comment by daledavies** [comment]
FYI the v1.1.3 release has been pushed to docker hub, let me know how you get on.

**Comment by darrenleesmith** [comment]
Dale. Thank you, that was almost a better and quicker service than what I usually receive in a strip club!
