### ISSUE TITLE
Installed but not showing info

### ISSUE THREAD

**Issue by KevoM** [daledavies/jump#25]
Hello, thanks for this new project
Install is fine through Docker, seems to work, but nothing except the background appears

```
 -------------------------------------------------------------
- Repopulating web root with application files.
- Check if backgrounds or sites volumes have been mounted.
   - Backgrounds directory is mapped... symlinking.
   - Sites directory is mapped... symlinking.
- All done! Starting nginx/php services now.
-------------------------------------------------------------
[06-Apr-2022 17:09:47] NOTICE: fpm is running, pid 17
[06-Apr-2022 17:09:47] NOTICE: ready to handle connections
192.168.1.82 - - [06/Apr/2022:17:10:03 +0000] "GET / HTTP/1.1" 200 1131 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36" "-" 0.091 0.090 . 
```

<img width="1792" alt="Capture d’écran 2022-04-06 à 19 22 49" src="https://user-images.githubusercontent.com/8274366/162032394-4c6538e2-22ab-4a13-975a-d7b6fbe58493.png">

**Comment by daledavies** [comment]
Howdy, could you post a screenshot of the console tab in your browser's Dev tools?

**Comment by KevoM** [comment]
Yes, here it is.

and the json is as recommended in the configuration page.

`{
    "default": {
        "nofollow": true,
        "icon": "my-default-icon.png",
        "newtab": false
    },
    "sites": [
        {
            "name": "Github",
            "url" : "https://github.com/daledavies/jump",
            "nofollow": false,
            "newtab": true
        },
        {
            "name": "Docker Hub",
            "url" : "https://hub.docker.com/r/daledavies/jump"
        },
        {
            "name": "Bitwarden",
            "url" : "https://bitwarden.example.com",
            "icon": "bitwarden.png",
            "tags": ["stuff"]
        },
        {
            "name": "Gitea",
            "url" : "https://git.example.com",
            "icon": "gitea.png",
            "tags": ["stuff"]
        },
        {
            "name": "Nextcloud",
            "url" : "https://cloud.example.com",
            "icon": "nextcloud.png",
            "tags": ["home", "stuff", "things"]
        },
        {
            "name": "Paperless",
            "url" : "https://paperless.example.com",
            "icon": "paperless.jpg",
            "tags": ["things", "home"]
        },
        {
            "name": "Google",
            "url" : "https://www.google.com",
            "nofollow": false
        }
    ]
}
`

**Comment by daledavies** [comment]
Sorry I should have asked this in my first comment, if you look in the network tab for /api/weatherdata.php, what's the response back from that? 

I think it is not liking the json returned from weatherdata.php, which could mean that it is producing an error rather than actual well formed json.

**Comment by KevoM** [comment]
It was indeed because I didn't edit the API key...
Removing the OWMAPIKEY's line that make it work ;)

Sorry for pointing out something obvious as an issue. Maybe you can comment the docker compose file ('# change this Key or remove it if not necessary') cause the error didn't clearly say why it happened.

Status 200 in the log and the console

Thanks for you help !

<img width="557" alt="Capture d’écran 2022-04-06 à 20 58 38" src="https://user-images.githubusercontent.com/8274366/162049627-c896d55c-09fb-40cf-beec-6a5f4290848b.png">

**Comment by daledavies** [comment]
Excellent I'm glad you got it working! I think I should update the readme to be clear like you said, also weatherdata PHP should probably return something other than 200. I'll add it to my to-do list 😄
