### ISSUE TITLE
Marquee Effect

### ISSUE THREAD

**Issue by darrenleesmith** [daledavies/jump#26]
Would it be possible to add a "Marquee Effect" for names of links? 

[https://www.w3docs.com/snippets/css/how-to-have-the-marquee-effect-without-using-the-marquee-tag-with-css-javascript-and-jquery.html#example-of-creating-a-horizontally-scrolling-text-without-the-lt-marquee-gt-tag-6](url)

Basically so the name text bounces left to right so you're able to see all the text.

**Comment by daledavies** [comment]
I totally understand the problem but I'm not sure a marquee effect is the best way to address it. I'll have a think about alternatives, thanks :)

**Comment by daledavies** [comment]
I've created a new release and tag for v1.1.4 and pushed a new image to docker hub, I hope this works OK for you :)

**Comment by darrenleesmith** [comment]
Hey Dale, I have pulled the latest, how do I change to the alternative view? (Sorry my brain isn't working today)

**Comment by daledavies** [comment]
Howdy. If you are using the docker container then set the `ALTLAYOUT` environment variable to the string `'true'`, if you have manually installed then edit the `altlayout` option in `config.php` to `true`.
