### ISSUE TITLE
Request: searchbar

### ISSUE THREAD

**Issue by dazWiLLiE** [daledavies/jump#29]
Nice work!

I have a request, how about having a searchbar (with optional custom search-engine address)?

Having Jump as a default newtab homepage, that would save quite a few steps.

**Comment by daledavies** [comment]
Howdy! 

Thank's for reaching out, I've been considering this for a while 😀

**Comment by daledavies** [comment]
This is now available in the v1.2.0 release... https://github.com/daledavies/jump/tree/v1.2.0

I'll push an updated image to Docker Hub later today.
