### ISSUE TITLE
Feature Request: ToDo list

### ISSUE THREAD

**Issue by frakman1** [daledavies/jump#30]
See [Momentum](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca?hl=en) start page for inspiration:

![image](https://user-images.githubusercontent.com/5826484/170998747-9351f356-8800-4c12-b346-6823378c7e9c.png)

Feature details [here](https://get.momentumdash.help/hc/en-us/articles/360012371413-Todo)

**Comment by daledavies** [comment]
Hi thanks again for your suggestion, I want to keep Jump simple and I think a to-do list app is a little too much for this use case. In particular I don't want Jump to depend on a database service so the to-do list would need to store it's data on the client, which might not be ideal if you want to see the items on multiple devices etc.

One thing I have been considering however is possibly integrating notifications from other app's via their API, so perhaps this might work if you have an external to-do list app and want reminders to show up your Jump startpage.
