### ISSUE TITLE
Feature Request: Quotations

### ISSUE THREAD

**Issue by frakman1** [daledavies/jump#31]
See [Momentum](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca?hl=en) start page for inspiration (Quote is along the bottom middle)

![image](https://user-images.githubusercontent.com/5826484/170999230-3e849571-38ae-429b-a883-0163ded4c4ae.png)

Feature details [here](https://get.momentumdash.help/hc/en-us/articles/360012256634-Quotes)

**Comment by daledavies** [comment]
Thanks for reaching out, I'll keep this in mind as a possible future enhancement.
