### ISSUE TITLE
feature request: background images from unsplash timeout

### ISSUE THREAD

**Issue by kjames2001** [daledavies/jump#36]
hi, thanks for this great homepage!

i have set it up with unsplash api and love random background from the internet. 

However, i download a lot, so sometimes the home page takes a while to load when internet traffic is busy.

So, i was wondering if you could set a timeout for unsplash, so that if it times out, jump gets a random background from the /background folder.

and kindly let us customize/config the timeout period plz.

thanks!

**Comment by daledavies** [comment]
Hi @kjames2001 

Thanks for reaching out, I never noticed this during development but I have actually just noticed something similar on my own server.

The Unsplash API can be quite slow so Jump caches API response and image data for the next image to be used, so after the cache is initially populated there shouldn't be a delay when loading the page.

There is a script that is called asynchronously from unsplashdata.php that keeps the cache updated for the next request, this makes a request to the API to get the metadata for a random image from one of the collections and then a second request to download the actual image data so it can be cached. I think this second request can sometimes time out and results in null data being cached.

I might look at how this can be better handled, also like you suggested it may be possible to fall back to a local image in the worst case. This would also help if the API ever goes down too.

Thanks :)

**Comment by kjames2001** [comment]
thanks for elaborating!

kindly note that Open Weather Map api does the same thing. both api delays the page open experience, at least for me.

hope we can load the page first before the apis.
