### ISSUE TITLE
feature request: allow custom URL for backgrounds

### ISSUE THREAD

**Issue by mprajescu** [daledavies/jump#37]
Hi. Just wanted to let you know you did a great job with jump. 
I absoluteley love it.
I would like to request a bit of improvement in my opinion. 

I am currently using Lorem Space (https://lorem.space/) to provide similar functionality for Unsplash, but I host my own backgrounds for different services. I simply point my URL to grab a wallpaper from the server with the desired resolution and with every new request, I get a different wallpaper.

This works great behind corporate firewalls where, unfortunatley, unsplash/pixabay and other services are blocked. 

Is it possible to implement the lorem.space URL request for backgrounds? 

Happy to provide more info if you need it.

**Comment by daledavies** [comment]
Howdy, thanks for reaching out. There is scope for something like a static `bgurl` option that you could stick any URL in and it will just use that for the CSS background-image URL, this would work for your use case and probably a few others too.

I'll add it to the backlog 🙂

**Comment by daledavies** [comment]
I've added an option for this in v1.2.2 (released today). You can now add a custom background provider via the `ALTBGPROVIDER` environment variable (if using Docker) or the `altbgprovider` parameter in `config.php`.

Thank you again for reaching out :)
