### ISSUE TITLE
Custom favicons

### ISSUE THREAD

**Issue by auridas330** [daledavies/jump#41]
Hey!
Any chance of a variable to have our custom favicons for the main jump website? At the moment I had to fork the build to change the favicon.png and rebuild lol.

**Comment by daledavies** [comment]
Absolutely yes! Thank you for reaching out 😀

This has been on my mind for a while as I'm actually not particularly happy with the current favicon anyway. I'm working on a few other things too but will include this in the next release.

**Comment by auridas330** [comment]
Thank you!

**Comment by daledavies** [comment]
Not a problem 😀

**Comment by daledavies** [comment]
Done! If you're using docker you should be able to get this now by pulling either the `v1.2.4` or `latest` tags :)

**Comment by daledavies** [comment]
Also, see the docker/docker-compose and favicon sections of the readme for more details.

**Comment by daledavies** [comment]
Browsers can be stubborn when it comes to refreshing the favicon, have you tried clearing cache and ctrl-f5? Maybe open dev tools (F12) and do ctrl-f5 etc.

Also if you browse directly to `/assets/images/favicon/icon.png` with a clear cache do you see the correct icon?

**Comment by auridas330** [comment]
Weirdly enough when I browse there there is no favicon image at all
You can have a look yourself at www.sibit.is

**Comment by daledavies** [comment]
I'm only able to use my phone at the minute but I do see one...

![Screenshot_20220719-182413](https://user-images.githubusercontent.com/4996546/179812007-b310ac95-d079-4df7-8b5c-f26ebe3fcea3.png)

**Comment by auridas330** [comment]
Lol im so confused haha
Well it works, maybe need to have a look at what cloudflare is caching. Thank you!

**Comment by daledavies** [comment]
Hey no problem, let me know if I can help

**Comment by auridas330** [comment]
After clearing the cloudflare cache it started appearing on my devices too. Thanks again!
