### ISSUE TITLE
Icons not updating

### ISSUE THREAD

**Issue by auridas330** [daledavies/jump#47]
So I have a weird issue.
If I add a new icon and configure the site.json the icon refuses to load on the website, but If I use any of the old one that were there in the folder it loads fine.

**Comment by daledavies** [comment]
Hmm that's an interesting one. Could you provide a screenshot of the javascript console from devtools and the sites.json?

**Comment by daledavies** [comment]
I guess also if you could get the docker logs that would be really handy, especially right at the start after you brought up the container.

**Comment by auridas330** [comment]
Actually... Never mind I fixed it...
I looked at the log and had this error message saying that jump did not have access to the file for some reason. So just edited the permissions and it fixed it.
Kind of embarrassing, sorry for opening an issue lol

**Comment by daledavies** [comment]
Not a problem whatever, thanks for reaching out.
