### ISSUE TITLE
Grammar Error in README.md

### ISSUE THREAD

**Issue by aarongill99** [daledavies/jump#48]
Grammar Error

startpage -> start page

**Comment by daledavies** [comment]
Thanks for reaching out. I'm a native speak but certainly not an expert in English language, but I'm not convinced this is an error. 

Although it is a relatively new and uncommon term, I see "startpage" in a similar way to "homepage", "online" or "email". These words have evolved to become simplified over time, with the simplified forms now being commonly accepted as correct.

In terms of examples online that demonstrate the use of "startpage" there are the following sites...

https://github.com/jnmcfly/awesome-startpage
https://www.reddit.com/r/startpages/

Browsing through the awesome-startpage repo there is a mix of both "start page" and "startpage" but I'm happy to leave it as t is for now.
