### ISSUE TITLE
Time is redundant in dashboard

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#5]
First of all thank you for creating jump.

I think time is not really required on dashboard because everyone can always see their system time. This is true even on phones. Instead of time something else like temperature can be shown to the user or maybe something else that is useful.

Besides I found that the time that I am seeing on dashboard is different from the time on my desktop clock. I believe it has chosen incorrect time zone as their is difference of almost 7 hours between the time.

**Comment by daledavies** [comment]
I can't imagine it being the architecture but you never know!

I'm trying to calculate the local time based on the difference from UTC returned from the open weather API. They have another API that I think actually returns the timezone so I can try using that.

I'll do some testing to see if I can recreate and fix it.

**Comment by quaintdev** [comment]
Time on dashboard: 17:10
System time: 11:40

It is difference of 5:30. I am in India so GMT+5:30 is my time zone.

**Comment by daledavies** [comment]
Thanks for this I'll look into it 🙂

**Comment by ddproxy** [comment]
May want to add an env var for the TZ offset, regardless of OpenWeather's API.

A docker container retrieves it's time from the host machine and can be modified (in general) with an env var of `TZ` when relying on the tzdata package.

**Comment by daledavies** [comment]
@quaintdev I have added what I think is a solution to the timezone issue to the following branch... https://github.com/daledavies/jump/tree/issue%235-timezonefix

Would you be OK to test?

**Comment by quaintdev** [comment]
It's working as expected. Thanks.

**Comment by daledavies** [comment]
Great news, thank you for your help.

**Comment by daledavies** [comment]
I've merged the patch into main and will continue to work on your feature request before closing this issue...

> I think time is not really required on dashboard because everyone can always see their system time. This is true even on phones. Instead of time something else like temperature can be shown to the user or maybe something else that is useful.
