### ISSUE TITLE
(Status: unknown) when using different port than 80

### ISSUE THREAD

**Issue by szczottie** [daledavies/jump#53]
Hi,
First of all I love Jump and I already started switch from Heimdall. The only issue I have is Jump won't show green status for services on ports other than 80, for example for proxmox running on port 8006 status is unknown. I would love to see all green for my services running on different ports :)

Thank you :)

Mack

**Comment by daledavies** [comment]
Thanks for reaching out! This is interesting, the guzzle library is used under the hood and should support requests to other ports, but it makes a HEAD request which could be blocked perhaps.

I'm thinking a further enhancement could be per-site options for the type of request and also maybe some global option to get more verbose logging or a cli script you could run via docker exec.

**Comment by daledavies** [comment]
I think it is also possible that Jump is making the request to your services via the internal docker network, so your services might be listening on a different port internally.

Further to this the IP address with which you access your services on the host wont be associated with the respective containers on docker's internal network. For example I could access jump via `127.0.0.1:8123` externally, but on the internal docker network I'd need to access it via `172.17.0.2:8080`.

I think additional per-site options mentioned in my previous comment but also including a different health check endpoint might be a good way forward.

**Comment by daledavies** [comment]
It is possible this might now be resolved with the work for issue #68. This has been included in the latest v1.3.1 release today, you can pull this from Docker Hub using either the daledavies/jump:latest or daledavies/jump:v1.3.1 tags.

Thanks for reporting this, I'll close the issue for now but feel free to repoen or open a new one if needed :)
