### ISSUE TITLE
Any advice for installing without composer?

### ISSUE THREAD

**Issue by ParoTheParrot** [daledavies/jump#54]
I downloaded all the mentioned packages and uploaded them to the vendor directory:
```
   "require": {
        "mustache/mustache": "~2.5",
        "arthurhoaro/favicon": "~1.0",
        "nette/caching": "^3.1",
        "nette/routing": "^3.0.2",
        "phlak/config": "^7.0",
        "nette/http": "^3.1",
        "unsplash/unsplash": "^2.5"
    }
```

But I get an error
`Fatal error: Uncaught Error: Class "Jump\Main" not found in /PATHONSERVER/jumpapp/index.php:21 Stack trace: #0 {main} thrown in /PATHONSERVER/jumpapp/index.php on line 21`

What is the  `/vendor/autoload.php`  file ?

I`ve no experience with composer  - sorry

**Comment by daledavies** [comment]
I don't think you're going to get this to work without installing the packages using composer, it does a lot more than just downloading the package repositories into the vendor directory.

**Comment by ParoTheParrot** [comment]
Do you have any advice for me to start using composer ("How to")
TIA!
