### ISSUE TITLE
Feature Request: Custom max-width

### ISSUE THREAD

**Issue by shulymn** [daledavies/jump#55]
Hi, 

At the moment I'm using Jump in a docker container (via Unraid), I really like it. I use it as my homepage.
I checked the css a bit and I saw that the max-width of the page was 650px (for .content), after changing it to 1000px it looks a bit better on a higher resolution (to me at least in 1440P).
But as you probably already know, the changes inside the docker container aren't persistent.

Is it possible to make it so we can set a custom max-width ?
Thanks.

**Comment by daledavies** [comment]
I can't see why not, I'll add this to my backlog :)

**Comment by daledavies** [comment]
I've committed a change to add a CUSTOMWIDTH option  as discussed. I'll push a new release of Jump soon but just want to look at a few other issues first.

**Comment by daledavies** [comment]
This has been included in the latest v1.3.1 release today, you can pull this from Docker Hub using either the daledavies/jump:latest or daledavies/jump:v1.3.1 tags.

Thanks for reporting this, I'll close the issue for now but feel free to repoen or open a new one if needed :)
