### ISSUE TITLE
Favicon is needed

### ISSUE THREAD

**Issue by quaintdev** [daledavies/jump#6]
I usually pin my dashboard so that I do not accidentally close it. In Firefox once we have pinned the tab it is reduced to favicon as shown below.  But because jump does not have favicon at the moment it shows the default icon which is not aesthetically pleasing. 

A nice favicon would also fit well with rest of jump dashboard. 

![image](https://user-images.githubusercontent.com/59229571/154417199-34502f36-c522-43e1-a000-77b9e88e7868.png)

**Comment by daledavies** [comment]
Yes I actually realised this myself last night, I'll find one 🙂

**Comment by daledavies** [comment]
Favicon added with this commit... https://github.com/daledavies/jump/commit/c81ce98a28da3959bcd580f7a95f85598335e52f

Although this is now in main branch it will be bundled with everything else that is part of milestone v1.0.3 for new docker image etc. 

Thanks again for your feedback @quaintdev :)

**Comment by quaintdev** [comment]
Thanks for quick fixes for both issues!
