### ISSUE TITLE
Add translations in different languages

### ISSUE THREAD

**Issue by AmadeusGraves** [daledavies/jump#61]
The application is not internationalized, that is to say, it is not translated into different languages, which is absolutely necessary, since users who speak different languages prefer it in their own language. This should be imperative in the development of the application, because the lack of this makes many users do not want to use this dashboard.

**Comment by AmadeusGraves** [comment]
Can you justify why this task has been closed?

**Comment by daledavies** [comment]
You came to small project with a sole developer and made a demand without offering any support, this is not a commercial project and I am offering it for free because I enjoy making things like this. 

If you do not like the fact that this is not internationalized and are not prepared to offer any help to change the fact then you are free to go and choose another project.

**Comment by daledavies** [comment]
I think when making requests you should be mindful of how the language you use might be interpreted. Your request comes across as a demand, your request would have been much better worded as follows and might not have been closed...

"Hey this looks like a great project, thanks for creating it. I wonder if there is a chance you might consider adding translations? I am not a coder but I do speak a number of languages so would be happy to provide the translations themselves"

**Comment by AmadeusGraves** [comment]
First of all, I have tested your project and I have given my opinion about it, the fact that you complain or answer that way because you are the only developer, which I didn't know and besides that I see 3 contributors in this project, is quite funny to me. 

If you don't accept people's criticisms, why are you making this project public in the first place? I am also in open-source projects and even if you are the only developer you should be open to what users can say, because they can help you to improve.

I only gave my opinion, I have not demanded anything, there may have been a confusion because English is not my main language, but that does not take away the fact of those answers.
