### ISSUE TITLE
Mac/Vivaldi: jump is using 25% CPU time, fans are running noisy

### ISSUE THREAD

**Issue by JarlMorgennebel** [daledavies/jump#67]
When switching to the Jump tab on Mac OS with Vivaldi,

CPU load start to reach 20% and more and fans start to be quite noisy. Switching to another tab will reduce CPU and fan noise.

**Comment by daledavies** [comment]
Thanks for reporting, I have not noticed this before but to be honest I've not been looking for it. Just tested in Firefox on Linux and I can see something similar. I'll do some profiling as soon as I can and see if I can fix it.

**Comment by daledavies** [comment]
I've been testing on both Firefox and Chrome in Linux and think I've narrowed this down to the animated loading SVG I've used for the icons, for me I'm seeing Jump's tab drop from ~9% CPU to almost nothing by removing the CSS that adds this image behind each icon. I imagine the CPU usage would scale with the number of sites that are on screen at the same time.

**Comment by daledavies** [comment]
Ok this should be fixed with the above commit. I'll package this and a few other things in a new release soon 😀

**Comment by daledavies** [comment]
This should hopefully be fixed with the v1.3.2 release so closing the issue. Thanks again, let me know how you get on :)
