### ISSUE TITLE
Time shown is incorrect

### ISSUE THREAD

**Issue by robinprice** [daledavies/jump#7]
I have set my lat / long correctly however the time does not show correctly. This assumes this feature is a factor of the time shown. 

In the screenshot below you’ll notice that the apps time is showing as 4 hours behind my actual time.

![AC2F5470-12CD-443F-B0F7-D4AFC44E2906](https://user-images.githubusercontent.com/46245864/154887953-30488a63-6f73-477a-867a-e5c4b8d8e8aa.jpeg)

**Comment by robinprice** [comment]
I also attempted to add TZ to the environment section of the docker compose. This yielded no change.

**Comment by robinprice** [comment]
Looks like this may be addressed from the following. 

https://github.com/daledavies/jump/issues/5

Apologies if a redundant issue and can be closed if so.

**Comment by daledavies** [comment]
The latest v1.0.3 should hopefully address this, could you pull the latest image and give it a try?

Thanks :)

**Comment by robinprice** [comment]
Confirmed fixed on 1.0.3

Thanks!

**Comment by daledavies** [comment]
No problem, thank you for the feedback 😀
