### ISSUE TITLE
Mobile view not scrollable

### ISSUE THREAD

**Issue by rauschgiftengel** [daledavies/jump#74]
As the topic says, if you have few more icons, in the mobile view  is not scrollable and the buttons for search, tags, time, weather are in front of the icons, so they are not clickable.

**Comment by daledavies** [comment]
I have reworked the mobile view a little, including making it scrollable. 

This has been included in the latest v1.3.1 release today, you can pull this from Docker Hub using either the `daledavies/jump:latest` or `daledavies/jump:v1.3.1` tags.

**Comment by Toucani** [comment]
Hey, just wanted to say thank you for fixing this!
Looks good, and now I can actually click more than first 9 bookmarks on my phone:)

**Comment by daledavies** [comment]
You're welcome! 😀
