### ISSUE TITLE
Request: Choice between 12 and 24 hour time

### ISSUE THREAD

**Issue by robinprice** [daledavies/jump#8]
Like the title notes, it would be a nice feature to be able to choose between 12 and 24 hour time.

**Comment by daledavies** [comment]
Can't see why not, I'll add it to the next milestone. Thanks for the request 😀

**Comment by daledavies** [comment]
This is ready for the v1.1.2 release :)

**Comment by daledavies** [comment]
The v1.1.2 release is out so I'm closing this issue. Hope you like it! :)
