### ISSUE TITLE
How to edit the CSS?

### ISSUE THREAD

**Issue by rwbronco** [daledavies/jump#96]
Every time I edit the CSS it seems to reset itself after a restart. This framework is new to me so I'm not sure entirely what's going on - but it looks like it's re-building the CSS from the scss files inside \assets\css\src maybe?

edit: also trying to replace the greeting with an image.

**Comment by flurmind** [comment]
Just build from source:
```
image: daledavies/jump 
#To build from source, comment previous line and uncomment below
#build: .   
```
